import Link from 'next/link'
import Head from 'next/head'

function Experiences() {
   return (
      <>
         <Head>
            <title>Experiences</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <Link href="/experiences">Test</Link>
      </>

   )
}

export default Experiences